name: 🌐 Build & Deploy Site (private S3 articles)

on:
  push:           # run on every push to main
    branches: [ main ]
  schedule:       # run nightly
    - cron: '0 2 * * *'
  workflow_dispatch:   # allow manual trigger

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo using your PAT (so we can push later)
      - name: Checkout main with PAT
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      # 2. Pull Markdown articles from your private S3 bucket
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}
      
      - name: Sync articles from S3
        run: |
          mkdir -p _thoughts
          aws s3 sync s3://elpunce-thoughts/ _thoughts/

      - name: List _thoughts after S3 sync
        run: |
          echo 'Fetched posts:'
          ls -R _thoughts || true

      # 3. Build the Jekyll site into docs/
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      
      - name: Install Jekyll
        run: gem install jekyll

      - name: Build site to docs/
        run: jekyll build --destination docs

      # 4. Stop GitHub Pages from re‑running Jekyll
      - name: Add .nojekyll
        run: |
          mkdir -p docs
          touch docs/.nojekyll

      # 5. Commit only docs/ (and CNAME) back to main
      - name: Commit built site
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: deploy site update"
          branch: main
          file_pattern: |
            docs/*
            docs/**/*
            CNAME
            docs/.nojekyll

