name: 🌐 Build & Deploy Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Pull down your repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Configure AWS creds (for S3 sync)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      # 3. Sync your private Markdown articles into _thoughts/
      - name: Sync articles from S3
        run: |
          mkdir -p _thoughts
          aws s3 sync s3://elpunce-articles/articles/ _thoughts/

      # 4. Setup Ruby & Jekyll
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x'
      - name: Install Jekyll dependencies
        run: |
          gem install bundler jekyll
          bundle install --jobs 4 --retry 3

      # 5. Build the site
      - name: Build site with Jekyll
        run: bundle exec jekyll build --destination _site

      # 6. Deploy the generated _site/ to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token:     ${{ secrets.GITHUB_TOKEN }}
          publish_branch:   gh-pages
          publish_dir:      ./_site