name: 📥 Sync Thoughts from S3

on:
  schedule:
    - cron: '0 2 * * *'     # daily at 02:00 UTC; adjust as you like
  workflow_dispatch:        # manual trigger

jobs:
  sync-thoughts:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo (full history so git-auto-commit can diff)
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Configure AWS creds for S3 access
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      # 3. Sync your private .md files into the _thoughts/ folder
      - name: Sync articles from S3
        run: |
          mkdir -p _thoughts
          aws s3 sync s3://elpunce-thoughts/ _thoughts/

      # 4. Commit any new or changed files back to main
      - name: Commit updated thoughts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: sync thoughts from s3"
          branch: main
          token: ${{ secrets.PAT }}
